# Generated by Django 4.2.6 on 2023-10-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('engine', models.CharField(max_length=40)),
            ],
        ),
    ]
